// PR Bot - Process /sandcastle comments on PRs
//
// This script scans open PRs for /sandcastle comments and processes them.
// It can either implement requested changes or ask for more information.
//
// Usage:
//   npx tsx .sandcastle/pr-bot/main.mts
// Or add to package.json:
//   "scripts": { "sandcastle-pr-bot": "npx tsx .sandcastle/pr-bot/main.mts" }

import * as sandcastle from "@ai-hero/sandcastle";
import { docker } from "@ai-hero/sandcastle/sandboxes/docker";
import { z } from "zod";
import { sandboxEnv } from "../shared/sandbox-env.mts";
import { createReviewAgent } from "../shared/review.mts";
import { execSync } from "child_process";
import fs from "fs";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Comment = {
  id: string;
  author: string;
  body: string;
  createdAt: string;
  isBotReply: boolean;
  sandcastleCommand?: string;
};

type PR = {
  number: number;
  title: string;
  body: string | null;
  headRefName: string;
};

type Thread = {
  pr: PR;
  comments: Comment[];
};

type PlanAction = {
  action: "implement";
  summary: string;
  context: string;
} | {
  action: "needs-info";
  questions: string[];
};

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const PLAN_SCHEMA = z.object({
  action: z.enum(["implement", "needs-info"]),
  summary: z.string().optional(),
  context: z.string().optional(),
  questions: z.array(z.string()).optional(),
});

// ---------------------------------------------------------------------------
// Helper Functions
// ---------------------------------------------------------------------------

const hasSandcastleCommand = (comment: Comment): boolean => {
  return comment.body.includes("/sandcastle");
};

const isBotReply = (comment: Comment): boolean => {
  return comment.body.includes("> *This was generated by AI during triage.*");
};

const extractSandcastleCommand = (commentBody: string): string | undefined => {
  const match = commentBody.match(/\/sandcastle\s+(.*)/);
  return match ? match[1] : undefined;
};

const getOpenPRs = async (): Promise<PR[]> => {
  try {
    const output = execSync(
      `gh pr list --state open --limit 100 --json number,title,body,headRefName`,
      { encoding: "utf-8" }
    );
    return JSON.parse(output);
  } catch (error) {
    console.error("Failed to fetch open PRs:", error);
    return [];
  }
};

const getCommentsForPR = async (prNumber: number): Promise<Comment[]> => {
  try {
    const output = execSync(
      `gh pr view ${prNumber} --json comments --jq '.comments[] | {id: .id, author: .author.login, body: .body, createdAt: .createdAt}'`,
      { encoding: "utf-8" }
    );

    const comments: Comment[] = output
      .split("\n")
      .filter(line => line.trim())
      .map(line => JSON.parse(line));

    // Process comments to identify bot replies and extract commands
    return comments.map(comment => ({
      ...comment,
      isBotReply: isBotReply(comment),
      sandcastleCommand: extractSandcastleCommand(comment.body)
    }));
  } catch (error) {
    console.error(`Failed to fetch comments for PR #${prNumber}:`, error);
    return [];
  }
};

const findUnhandledSandcastleComments = (comments: Comment[]): Comment[] => {
  const sandcastleComments = comments.filter(hasSandcastleCommand);
  const botReplies = new Set(
    comments
      .filter(comment => comment.isBotReply)
      .map(comment => comment.createdAt)
  );

  // Filter out comments that already have bot replies
  return sandcastleComments.filter(comment => {
    // Simple heuristic: if there's a bot reply after this comment, it's handled
    // In a real implementation, you'd want to track which comment each bot reply responds to
    return !Array.from(botReplies).some(replyTime => 
      new Date(replyTime) > new Date(comment.createdAt)
    );
  });
};

const postComment = async (prNumber: number, body: string): Promise<void> => {
  try {
    const commentFileName = `pr-${prNumber}-comment.md`;
    fs.writeFileSync(commentFileName, body);
    execSync(
      `gh pr comment ${prNumber} --body-file ${commentFileName}`,
      { stdio: "inherit" }
    );
    fs.rmSync(commentFileName);
  } catch (error) {
    console.error(`Failed to post comment on PR #${prNumber}:`, error);
  }
};

const pushBranch = async (branchName: string): Promise<void> => {
  try {
    execSync(
      `git push --set-upstream origin ${branchName}`,
      { stdio: "inherit" }
    );
  } catch (error) {
    console.error(`Failed to push branch ${branchName}:`, error);
  }
};

// ---------------------------------------------------------------------------
// Implementation Agent
// ---------------------------------------------------------------------------

const createImplementAgent = async (sandboxEnv: any, pr: PR, changeRequest: string, context: string) => {
  return async (): Promise<void> => {
    // Run the implement agent to make the requested changes
    await sandcastle.run({
      sandbox: docker({ env: sandboxEnv }),
      name: "pr-implement-agent",
      maxIterations: 1,
      agent: sandcastle.pi("openrouter/qwen/qwen3-coder"),
      promptFile: "./.sandcastle/pr-bot/implement-prompt.md",
      promptArgs: { 
        PR_NUMBER: pr.number.toString(),
        PR_TITLE: pr.title,
        PR_BRANCH: pr.headRefName,
        CHANGE_REQUEST: changeRequest,
        CONTEXT: context
      },
      completionSignal: "<promise>COMPLETE</promise>"
    });
  };
};

const createReviewAgent = async (sandboxEnv: any, pr: PR) => {
  return async (): Promise<void> => {
    // Run the review agent to review the changes
    await sandcastle.run({
      sandbox: docker({ env: sandboxEnv }),
      name: "pr-review-agent",
      maxIterations: 1,
      agent: sandcastle.pi("openrouter/deepseek/deepseek-v4-pro"),
      promptFile: "./.sandcastle/shared/review-prompt.md",
      promptArgs: { BRANCH: pr.headRefName },
      completionSignal: "<promise>COMPLETE</promise>"
    });
  };
};

// ---------------------------------------------------------------------------
// Main Processing Functions
// ---------------------------------------------------------------------------
const processPRComments = async (pr: PR, comments: Comment[]): Promise<boolean> => {
  console.log(`Processing PR #${pr.number}: ${pr.title}`);
  
  const unhandledComments = findUnhandledSandcastleComments(comments);
  
  if (unhandledComments.length === 0) {
    console.log(`No unhandled /sandcastle comments on PR #${pr.number}`);
    return false;
  }

  console.log(`Found ${unhandledComments.length} unhandled /sandcastle comments`);

  // Checkout the PR branch
  try {
    execSync(`git fetch origin ${pr.headRefName}`, { stdio: "inherit" });
    execSync(`git checkout ${pr.headRefName}`, { stdio: "inherit" });
  } catch (error) {
    console.error(`Failed to checkout branch ${pr.headRefName}:`, error);
    return false;
  }

  let changesMade = false;

  // Process each unhandled comment
  for (const comment of unhandledComments) {
    console.log(`Processing comment from ${comment.author}: ${comment.sandcastleCommand}`);
    
    const thread: Thread = {
      pr,
      comments: comments.filter(c => 
        new Date(c.createdAt) <= new Date(comment.createdAt)
      )
    };

    // Create plan agent to analyze the comment
    const planAgent = await sandcastle.run({
      sandbox: docker({ env: sandboxEnv }),
      name: "pr-plan-agent",
      maxIterations: 1,
      agent: sandcastle.pi("openrouter/anthropic/claude-haiku-4.5"),
      promptFile: "./.sandcastle/pr-bot/plan-prompt.md",
      promptArgs: { THREAD_JSON: JSON.stringify(thread) },
      output: sandcastle.Output.object({ tag: "plan", schema: PLAN_SCHEMA }),
    });

    const plan = planAgent.output as PlanAction;

    if (plan.action === "needs-info") {
      // Ask for more information
      const questionsList = plan.questions?.map(q => `- ${q}`).join("\n") || "";
      const response = `> *This was generated by AI during triage.*\n\nI need more information to process your request:\n\n${questionsList}`;
      await postComment(pr.number, response);
    } else if (plan.action === "implement") {
      // Implement the requested change
      console.log(`Implementing: ${plan.summary}`);
      
      // Create a sandbox for the implementation
      const sandbox = await sandcastle.createSandbox({
        branch: pr.headRefName,
        sandbox: docker({ env: sandboxEnv }),
        hooks: {
          sandbox: { onSandboxReady: [{ command: "pnpm install" }] },
        },
        copyToWorktree: ["node_modules"],
      });
      
      try {
        // Run the implement agent
        const implementAgent = await createImplementAgent(sandboxEnv, pr, comment.sandcastleCommand || "", plan.context || "");
        await implementAgent();
        
        // Run the review agent
        const reviewAgent = await createReviewAgent(sandboxEnv, pr);
        await reviewAgent();
        
        // Post a summary response
        const response = `> *This was generated by AI during triage.*\n\nI've implemented the requested change: ${plan.summary}`;
        await postComment(pr.number, response);
        
        changesMade = true;
      } finally {
        await sandbox.close();
      }
    }
  }

  // If changes were made, push the branch
  if (changesMade) {
    await pushBranch(pr.headRefName);
  }

  // Switch back to main branch
  execSync(`git checkout main`, { stdio: "inherit" });
  
  return true;
};

// ---------------------------------------------------------------------------
// Main Function
// ---------------------------------------------------------------------------
async function main() {
  console.log("Starting PR Bot...");
  
  const prs = await getOpenPRs();
  
  if (prs.length === 0) {
    console.log("No open PRs found.");
    return;
  }

  console.log(`Found ${prs.length} open PRs`);
  
  let processedAny = false;
  
  // Process PRs one by one
  for (const pr of prs) {
    const comments = await getCommentsForPR(pr.number);
    const processed = await processPRComments(pr, comments);
    
    if (processed) {
      processedAny = true;
    }
  }
  
  if (!processedAny) {
    console.log("No unhandled /sandcastle comments found.");
  } else {
    console.log("Finished processing PR comments.");
  }
}

main().catch(console.error);