// PR Bot - Process /sandcastle comments on PRs
//
// This script scans open PRs for /sandcastle comments and processes them.
// It can either implement requested changes or ask for more information.
//
// Usage:
//   npx tsx .sandcastle/pr-bot/main.mts
// Or add to package.json:
//   "scripts": { "sandcastle-pr-bot": "npx tsx .sandcastle/pr-bot/main.mts" }

import * as sandcastle from "@ai-hero/sandcastle";
import { docker } from "@ai-hero/sandcastle/sandboxes/docker";
import { z } from "zod";
import { sandboxEnv } from "../shared/sandbox-env.mts";
import { SandboxEnv } from "../shared/types";
import { execSync } from "child_process";
import fs from "fs";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Comment = {
  id: string;
  author: string;
  body: string;
  createdAt: string;
  isBotReply: boolean;
  sandcastleCommand?: string;
  isReviewComment: boolean;
};

type PR = {
  number: number;
  title: string;
  body: string | null;
  headRefName: string;
};

type Thread = {
  pr: PR;
  comments: Comment[];
};

type PlanAction = {
  action: "implement";
  summary: string;
  context: string;
} | {
  action: "needs-info";
  questions: string[];
};

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const BOT_REPLY_PREFIX = "> *This was generated by AI during triage.*";

const PLAN_SCHEMA = z.object({
  action: z.enum(["implement", "needs-info"]),
  summary: z.string().optional(),
  context: z.string().optional(),
  questions: z.array(z.string()).optional(),
});

const ISSUE_COMMENT_SCHEMA = z.object({
  id: z.string(),
  author: z.string(),
  body: z.string(),
  createdAt: z.string(),
});

const REVIEW_COMMENT_SCHEMA = z.object({
  id: z.string(),
  author: z.string(),
  body: z.string(),
  created_at: z.string(),
});

const ISSUE_OUTPUT_SCHEMA = z.string().transform((s) =>
  s.split("\n").filter(l => l.trim()).map(l =>
    ISSUE_COMMENT_SCHEMA.parse(JSON.parse(l))
  )
);

const REVIEW_OUTPUT_SCHEMA = z.string().transform((s) =>
  s.split("\n").filter(l => l.trim()).map(l =>
    REVIEW_COMMENT_SCHEMA.parse(JSON.parse(l))
  )
);

// ---------------------------------------------------------------------------
// Helper Functions
// ---------------------------------------------------------------------------

const hasSandcastleCommand = (comment: Comment): boolean => {
  return comment.body.includes("/sandcastle");
};

const isBotReply = (comment: Comment): boolean => {
  return comment.body.includes(BOT_REPLY_PREFIX);
};

const extractSandcastleCommand = (commentBody: string): string | undefined => {
  const match = commentBody.match(/\/sandcastle\s+(.*)/);
  return match ? match[1] : undefined;
};

const getOpenPRs = async (): Promise<PR[]> => {
  try {
    const output = execSync(
      `gh pr list --state open --limit 100 --json number,title,body,headRefName`,
      { encoding: "utf-8" }
    );
    return JSON.parse(output);
  } catch (error) {
    console.error("Failed to fetch open PRs:", error);
    return [];
  }
};

const getCommentsForPR = async (prNumber: number): Promise<Comment[]> => {
  try {
    // Issue-level comments
    const issueOutput = execSync(
      `gh pr view ${prNumber} --json comments --jq '.comments[] | {id: .id, author: .author.login, body: .body, createdAt: .createdAt}'`,
      { encoding: "utf-8" }
    );

    const rawIssueComments = ISSUE_OUTPUT_SCHEMA.parse(issueOutput);
    const issueComments: Comment[] = rawIssueComments.map(c => ({
      ...c,
      isReviewComment: false,
      isBotReply: false,
    }));

    // Review comments (attached to files/lines)
    const reviewOutput = execSync(
      `gh api "repos/:owner/:repo/pulls/${prNumber}/comments" --jq '.[] | {id: (.id | tostring), author: .user.login, body: .body, createdAt: .created_at}'`,
      { encoding: "utf-8" }
    );

    const rawReviewComments = REVIEW_OUTPUT_SCHEMA.parse(reviewOutput);
    const reviewComments: Comment[] = rawReviewComments.map(c => ({
      ...c,
      createdAt: c.created_at,
      isReviewComment: true,
      isBotReply: false,
    }));

    const allComments = [...issueComments, ...reviewComments];

    return allComments.map(comment => ({
      ...comment,
      isBotReply: isBotReply(comment),
      sandcastleCommand: extractSandcastleCommand(comment.body)
    }));
  } catch (error) {
    console.error(`Failed to fetch comments for PR #${prNumber}:`, error);
    return [];
  }
};

const findUnhandledSandcastleComments = (comments: Comment[]): Comment[] => {
  const sandcastleComments = comments.filter(hasSandcastleCommand);

  const latestBotReplyTime = Math.max(
    0,
    ...comments
      .filter(comment => comment.isBotReply)
      .map(comment => new Date(comment.createdAt).getTime())
  );

  if (latestBotReplyTime === 0) return sandcastleComments;

  return sandcastleComments.filter(
    comment => new Date(comment.createdAt).getTime() > latestBotReplyTime
  );
};

const postComment = async (prNumber: number, body: string, replyTo?: Comment): Promise<void> => {
  const commentFileName = `pr-${prNumber}-comment.md`;
  try {
    if (replyTo?.isReviewComment && replyTo.reviewCommentId) {
      // Reply to review comment via API
      const escapedBody = body.replace(/'/g, "'\\''");
      execSync(
        `gh api "repos/:owner/:repo/pulls/${prNumber}/comments" -f body='${escapedBody}' -f in_reply_to=${replyTo.id}`,
        { stdio: "inherit" }
      );
    } else {
      // Reply to issue comment via @mention
      const replyBody = replyTo ? `@${replyTo.author} ${body}` : body;
      fs.writeFileSync(commentFileName, replyBody);
      execSync(
        `gh pr comment ${prNumber} --body-file ${commentFileName}`,
        { stdio: "inherit" }
      );
    }
  } catch (error) {
    console.error(`Failed to post comment on PR #${prNumber}:`, error);
  } finally {
    try { fs.rmSync(commentFileName); } catch { /* best effort cleanup */ }
  }
};

const pushBranch = async (branchName: string): Promise<void> => {
  try {
    execSync(
      `git push --set-upstream origin ${branchName}`,
      { stdio: "inherit" }
    );
  } catch (error) {
    console.error(`Failed to push branch ${branchName}:`, error);
  }
};

// ---------------------------------------------------------------------------
// Agent Functions
// ---------------------------------------------------------------------------

const runImplementAgent = (sandboxEnv: SandboxEnv, pr: PR, changeRequest: string, context: string) => {
  return sandcastle.run({
    sandbox: docker({ env: sandboxEnv }),
    name: "pr-implement-agent",
    maxIterations: 1,
    agent: sandcastle.pi("openrouter/qwen/qwen3-coder"),
    promptFile: "./.sandcastle/pr-bot/implement-prompt.md",
    promptArgs: {
      PR_NUMBER: pr.number.toString(),
      PR_TITLE: pr.title,
      PR_BRANCH: pr.headRefName,
      CHANGE_REQUEST: changeRequest,
      CONTEXT: context
    },
    completionSignal: "<promise>COMPLETE</promise>"
  });
};

const runReviewAgent = (sandboxEnv: SandboxEnv, pr: PR) => {
  return sandcastle.run({
    sandbox: docker({ env: sandboxEnv }),
    name: "pr-review-agent",
    maxIterations: 1,
    agent: sandcastle.pi("openrouter/deepseek/deepseek-v4-pro"),
    promptFile: "./.sandcastle/shared/review-prompt.md",
    promptArgs: { BRANCH: pr.headRefName },
    completionSignal: "<promise>COMPLETE</promise>"
  });
};

// ---------------------------------------------------------------------------
// Main Processing Functions
// ---------------------------------------------------------------------------
const processPRComments = async (pr: PR, comments: Comment[]): Promise<boolean> => {
  console.log(`Processing PR #${pr.number}: ${pr.title}`);
  
  const unhandledComments = findUnhandledSandcastleComments(comments);
  
  if (unhandledComments.length === 0) {
    console.log(`No unhandled /sandcastle comments on PR #${pr.number}`);
    return false;
  }

  console.log(`Found ${unhandledComments.length} unhandled /sandcastle comments`);

  try {
    execSync(`git fetch origin ${pr.headRefName}`, { stdio: "inherit" });
  } catch (error) {
    console.error(`Failed to checkout branch ${pr.headRefName}:`, error);
    return false;
  }

  let changesMade = false;

  for (const comment of unhandledComments) {
    console.log(`Processing comment from ${comment.author}: ${comment.sandcastleCommand}`);
    
    const thread: Thread = {
      pr,
      comments: comments.filter(c => 
        new Date(c.createdAt) <= new Date(comment.createdAt)
      )
    };

    //TODO At this point, the bot should look a the issue to see the work it has alredy completed for additional context
    // This context should be passed in to the plan agent

    // Create plan agent to analyze the comment
    const planAgent = await sandcastle.run({
      sandbox: docker({ env: sandboxEnv }),
      name: "pr-plan-agent",
      maxIterations: 1,
      agent: sandcastle.pi("openrouter/anthropic/claude-haiku-4.5"),
      promptFile: "./.sandcastle/pr-bot/plan-prompt.md",
      promptArgs: { THREAD_JSON: JSON.stringify(thread) },
      output: sandcastle.Output.object({ tag: "plan", schema: PLAN_SCHEMA }),
    });

    const plan = planAgent.output as PlanAction;

    if (plan.action === "needs-info") {
      const questionsList = plan.questions?.map(q => `- ${q}`).join("\n") || "";
      const response = `${BOT_REPLY_PREFIX}\n\nI need more information to process your request:\n\n${questionsList}`;
      await postComment(pr.number, response, comment);
    } else if (plan.action === "implement") {
      console.log(`Implementing: ${plan.summary}`);

      const sandbox = await sandcastle.createSandbox({
        branch: pr.headRefName,
        sandbox: docker({ env: sandboxEnv }),
        hooks: {
          sandbox: { onSandboxReady: [{ command: "pnpm install" }] },
        },
        copyToWorktree: ["node_modules"],
      });
      
      try {
        await runImplementAgent(sandboxEnv, pr, comment.sandcastleCommand || "", plan.context || "");
        await runReviewAgent(sandboxEnv, pr);

        const response = `${BOT_REPLY_PREFIX}\n\nI've implemented the requested change: ${plan.summary}`;
        await postComment(pr.number, response, comment);
        
        changesMade = true;
      } finally {
        await sandbox.close();
      }
    }
  }

  if (changesMade) {
    await pushBranch(pr.headRefName);
  }

  execSync(`git checkout main`, { stdio: "inherit" });

  return true;
};

// ---------------------------------------------------------------------------
// Main Function
// ---------------------------------------------------------------------------
async function main() {
  console.log("Starting PR Bot...");
  
  const prs = await getOpenPRs();
  
  if (prs.length === 0) {
    console.log("No open PRs found.");
    return;
  }

  console.log(`Found ${prs.length} open PRs`);
  
  let processedAny = false;

  for (const pr of prs) {
    const comments = await getCommentsForPR(pr.number);
    const processed = await processPRComments(pr, comments);
    
    if (processed) {
      processedAny = true;
    }
  }
  
  if (!processedAny) {
    console.log("No unhandled /sandcastle comments found.");
  } else {
    console.log("Finished processing PR comments.");
  }
}

main().catch(console.error);