import { z } from "zod";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type Comment = {
  id: string;
  author: string;
  body: string;
  createdAt: string;
  isBotReply: boolean;
  sandcastleCommand?: string;
  isReviewComment: boolean;
  /** Review comment file context (empty for issue comments) */
  file?: string;
  line?: number;
  diffHunk?: string;
};

export type PR = {
  number: number;
  title: string;
  body: string | null;
  headRefName: string;
};

export type Thread = {
  pr: PR;
  comments: Comment[];
};

export type PlanAction = {
  action: "implement";
  summary: string;
  context: string;
} | {
  action: "needs-info";
  questions: string[];
};

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

export const BOT_REPLY_PREFIX = "> *This was generated by AI during triage.*";

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

export const PLAN_SCHEMA = z.object({
  action: z.enum(["implement", "needs-info"]),
  summary: z.string().optional(),
  context: z.string().optional(),
  questions: z.array(z.string()).optional(),
});

export const ISSUE_COMMENTS_RESPONSE = z.object({
  comments: z.array(z.object({
    id: z.string(),
    author: z.object({ login: z.string() }),
    body: z.string(),
    createdAt: z.string(),
  })),
});

export const REVIEW_COMMENTS_RESPONSE = z.array(z.object({
  id: z.number(),
  user: z.object({ login: z.string() }),
  body: z.string(),
  created_at: z.string(),
  path: z.string(),
  line: z.number().nullable().optional(),
  diff_hunk: z.string(),
}));
