import { z } from "zod";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type Reactions = {
  totalCount: number;
  plusOne: number;
  minusOne: number;
  laugh: number;
  hooray: number;
  confused: number;
  heart: number;
  rocket: number;
  eyes: number;
};

export type Comment = {
  id: string;
  author: string;
  body: string;
  createdAt: string;
  isBotReply: boolean;
  sandcastleCommand?: string;
  isReviewComment: boolean;
  /** Review comment file context (empty for issue comments) */
  file?: string;
  line?: number;
  diffHunk?: string;
  reactions: Reactions;
};

export type PR = {
  number: number;
  title: string;
  body: string | null;
  headRefName: string;
};

export type Thread = {
  pr: PR;
  comments: Comment[];
};

export type PlanAction = {
  action: "implement";
  summary: string;
  context: string;
} | {
  action: "needs-info";
  questions: string[];
};

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

export const BOT_REPLY_PREFIX = "> *This was generated by AI during triage.*";

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

export const PLAN_SCHEMA = z.object({
  action: z.enum(["implement", "needs-info"]),
  summary: z.string().optional(),
  context: z.string().optional(),
  questions: z.array(z.string()).optional(),
});

const reactionsSchema = z.object({
  total_count: z.number(),
  "+1": z.number(),
  "-1": z.number(),
  laugh: z.number(),
  hooray: z.number(),
  confused: z.number(),
  heart: z.number(),
  rocket: z.number(),
  eyes: z.number(),
});

export const ISSUE_COMMENTS_RESPONSE = z.array(z.object({
  id: z.number(),
  user: z.object({ login: z.string() }),
  body: z.string(),
  created_at: z.string(),
  reactions: reactionsSchema.optional().default({
    total_count: 0,
    "+1": 0,
    "-1": 0,
    laugh: 0,
    hooray: 0,
    confused: 0,
    heart: 0,
    rocket: 0,
    eyes: 0,
  }),
}));

export const REVIEW_COMMENTS_RESPONSE = z.array(z.object({
  id: z.number(),
  user: z.object({ login: z.string() }),
  body: z.string(),
  created_at: z.string(),
  path: z.string(),
  line: z.number().nullable().optional(),
  diff_hunk: z.string(),
  reactions: reactionsSchema.optional().default({
    total_count: 0,
    "+1": 0,
    "-1": 0,
    laugh: 0,
    hooray: 0,
    confused: 0,
    heart: 0,
    rocket: 0,
    eyes: 0,
  }),
}));
